# dnf module disable nginx -y
# dnf module enable nginx:1.24 -y
# dnf install nginx -y
#
# rm -rf /usr/share/nginx/html/*
# curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
#
# rm -f /etc/nginx/nginx.conf
# cp nginx.conf /etc/nginx/nginx.conf
#
# cd /usr/share/nginx/html
# unzip /tmp/frontend.zip
#
#
# systemctl enable nginx
# systemctl restart nginx

- name: Frontend Setup
  hosts: all
  become: true
  tasks:
    - name: Install Nginx 1.24
      ansible.builtin.dnf:
        name: '@nginx:1.24'
        state: present

    - name: Remove default html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Create default html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download and extract app content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Copy nginx config file
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Start nginx service
      ansible.builtin.systemd_service:
        state: restarted
        name: nginx
        enabled: true