# cp rabbitmq.repo /etc/yum.repos.d/rabbitmq.repo
#
# dnf install rabbitmq-server -y
# systemctl enable rabbitmq-server
# systemctl restart rabbitmq-server
#
# rabbitmqctl add_user roboshop roboshop123
# rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"

- name: Rabbitmq Setup
  hosts: all
  become: true
  tasks:
    - name: Copy RabbitMQ repo file
      ansible.builtin.copy:
        src: rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo

    - name: Install RabbitMQ server
      ansible.builtin.dnf:
        name: rabbitmq-server
        state: present

    - name: Start RabbitMQ Server service
      ansible.builtin.systemd_service:
        state: restarted
        name: rabbitmq-server
        enabled: true

    - name: Create app user in rabbitmq
      ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123 ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"